### ISSUE TITLE
Newer Kinect model 1473  errors out - "Unable to open specified kinect". Works fine with model 1414

### ISSUE THREAD

**Issue by mirzashah** [ros-drivers/freenect_stack#12]
I just bought a new set of Kinects for Xbox with model number 1473. This article http://idav.ucdavis.edu/~okreylos/ResDev/Kinect/MainPage.html explains the difference, but in a nutshell...the newer version updates the hardware to work with Kinect for Windows protocols.

This seems to break functionality with libfreenect. The older Kinect for XBox model (1414) had no problems.  The problems are:

 * The device id now is reported as 000000000000000. The new model breaks the query protocol I assume.
 * The device no longer reports a motor in lsusb (Xbox NUI Motor)
 * I am able to use the libfreenect-demos (freenect-glview) package and everything works great in Ubuntu 14.04 LTS. I'm guessing libfreenect has been updated...but something in the ROS package might be out of line.
 * This problem is in both Trusty and Precise
 * openni_launch seems to work fine...openni2_launch does not. 
 * Helpful links
   * http://forum.openframeworks.cc/t/ofxkinect-issue-with-kinect-model-1473/11632/7
   * https://github.com/OpenKinect/libfreenect/pull/325
   * http://answers.ros.org/question/61542/kinect-xbox360-new-model-1473-has-problems-example-serial-number-soundcard/

Output of lsusb:
 Bus 002 Device 005: ID 05e3:0727 Genesys Logic, Inc. microSD Reader/Writer 
 Bus 002 Device 004: ID 8087:07d6 Intel Corp. 
 Bus 002 Device 007: ID 045e:02ae Microsoft Corp. Xbox NUI Camera 
 Bus 002 Device 006: ID 045e:02ad Microsoft Corp. Xbox NUI Audio
 Bus 002 Device 003: ID 045e:02c2 Microsoft Corp. 
 Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
 Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
 Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
 Bus 003 Device 004: ID 046d:c52e Logitech, Inc. 
 Bus 003 Device 003: ID 0d8c:013c C-Media Electronics, Inc. CM108 Audio Controller
 Bus 003 Device 002: ID 1a40:0101 Terminus Technology Inc. 4-Port HUB
 Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
 Bus 001 Device 003: ID 2232:1018  
 Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
 Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Output of roslaunch freenect_launch freenect_launch:
 ROS_MASTER_URI=http://localhost:11311
 
 core service [/rosout] found
 process[camera/camera_nodelet_manager-1]: started with pid [1421]
 [ INFO] [1406340292.910138575]: Initializing nodelet with 4 worker threads.
 process[camera/driver-2]: started with pid [1444]
 process[camera/debayer-3]: started with pid [1462]
 process[camera/rectify_mono-4]: started with pid [1491]
 [ INFO] [1406340293.320945433]: Number devices connected: 1
 [ INFO] [1406340293.321044568]: 1. device on bus 000:00 is a Xbox NUI Camera (2ae) from Microsoft (45e) with serial id '0000000000000000'
 [ INFO] [1406340293.321722756]: Searching for device with index = 1
 [ INFO] [1406340293.336926894]: No matching device found.... waiting for devices. Reason: [ERROR] Unable to open specified kinect
 process[camera/rectify_color-5]: started with pid [1535]
 process[camera/rectify_ir-6]: started with pid [1572]
 process[camera/depth_rectify_depth-7]: started with pid [1660]
 process[camera/depth_metric_rect-8]: started with pid [1706]
 process[camera/depth_metric-9]: started with pid [1748]
 process[camera/depth_points-10]: started with pid [1795]
 process[camera/register_depth_rgb-11]: started with pid [1828]
 process[camera/points_xyzrgb_sw_registered-12]: started with pid [1881]
 process[camera/depth_registered_rectify_depth-13]: started with pid [1914]
 process[camera/points_xyzrgb_hw_registered-14]: started with pid [1959]
 process[camera/disparity_depth-15]: started with pid [2014]
 process[camera/disparity_registered_sw-16]: started with pid [2033]
 process[camera/disparity_registered_hw-17]: started with pid [2082]
 process[camera_base_link-18]: started with pid [2116]
 process[camera_base_link1-19]: started with pid [2157]
 process[camera_base_link2-20]: started with pid [2192]
 process[camera_base_link3-21]: started with pid [2230]
 [ INFO] [1406340296.338296397]: Number devices connected: 1
 [ INFO] [1406340296.338637476]: 1. device on bus 000:00 is a Xbox NUI Camera (2ae) from Microsoft (45e) with serial id '0000000000000000'
 [ INFO] [1406340296.340908036]: Searching for device with index = 1
 [ INFO] [1406340296.342048120]: No matching device found.... waiting for devices. Reason: [ERROR] Unable to open specified kinect
 [ INFO] [1406340299.343443561]: Number devices connected: 1
 [ INFO] [1406340299.343618105]: 1. device on bus 000:00 is a Xbox NUI Camera (2ae) from Microsoft (45e) with serial id '0000000000000000'
 [ INFO] [1406340299.346420492]: Searching for device with index = 1
 [ INFO] [1406340299.347807542]: No matching device found.... waiting for devices. Reason: [ERROR] Unable to open specified kinect
 [ INFO] [1406340302.349236789]: Number devices connected: 1
 [ INFO] [1406340302.349391321]: 1. device on bus 000:00 is a Xbox NUI Camera (2ae) from Microsoft (45e) with serial id '0000000000000000'

However, it seems libfreenect is not able to query the serial number.

Output of lsusb:
 Bus 002 Device 005: ID 05e3:0727 Genesys Logic, Inc. microSD Reader/Writer 
 Bus 002 Device 004: ID 8087:07d6 Intel Corp. 
 Bus 002 Device 007: ID 045e:02ae Microsoft Corp. Xbox NUI Camera 
 Bus 002 Device 006: ID 045e:02ad Microsoft Corp. Xbox NUI Audio
 Bus 002 Device 003: ID 045e:02c2 Microsoft Corp. 
 Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
 Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
 Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
 Bus 003 Device 004: ID 046d:c52e Logitech, Inc. 
 Bus 003 Device 003: ID 0d8c:013c C-Media Electronics, Inc. CM108 Audio Controller
 Bus 003 Device 002: ID 1a40:0101 Terminus Technology Inc. 4-Port HUB
 Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
 Bus 001 Device 003: ID 2232:1018  
 Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
 Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Output of roslaunch freenect_launch freenect_launch:
 ROS_MASTER_URI=http://localhost:11311
 
 core service [/rosout] found
 process[camera/camera_nodelet_manager-1]: started with pid [1421]
 [ INFO] [1406340292.910138575]: Initializing nodelet with 4 worker threads.
 process[camera/driver-2]: started with pid [1444]
 process[camera/debayer-3]: started with pid [1462]
 process[camera/rectify_mono-4]: started with pid [1491]
 [ INFO] [1406340293.320945433]: Number devices connected: 1
 [ INFO] [1406340293.321044568]: 1. device on bus 000:00 is a Xbox NUI Camera (2ae) from Microsoft (45e) with serial id '0000000000000000'
 [ INFO] [1406340293.321722756]: Searching for device with index = 1
 [ INFO] [1406340293.336926894]: No matching device found.... waiting for devices. Reason: [ERROR] Unable to open specified kinect
 process[camera/rectify_color-5]: started with pid [1535]
 process[camera/rectify_ir-6]: started with pid [1572]
 process[camera/depth_rectify_depth-7]: started with pid [1660]
 process[camera/depth_metric_rect-8]: started with pid [1706]
 process[camera/depth_metric-9]: started with pid [1748]
 process[camera/depth_points-10]: started with pid [1795]
 process[camera/register_depth_rgb-11]: started with pid [1828]
 process[camera/points_xyzrgb_sw_registered-12]: started with pid [1881]
 process[camera/depth_registered_rectify_depth-13]: started with pid [1914]
 process[camera/points_xyzrgb_hw_registered-14]: started with pid [1959]
 process[camera/disparity_depth-15]: started with pid [2014]
 process[camera/disparity_registered_sw-16]: started with pid [2033]
 process[camera/disparity_registered_hw-17]: started with pid [2082]
 process[camera_base_link-18]: started with pid [2116]
 process[camera_base_link1-19]: started with pid [2157]
 process[camera_base_link2-20]: started with pid [2192]
 process[camera_base_link3-21]: started with pid [2230]
 [ INFO] [1406340296.338296397]: Number devices connected: 1
 [ INFO] [1406340296.338637476]: 1. device on bus 000:00 is a Xbox NUI Camera (2ae) from Microsoft (45e) with serial id '0000000000000000'
 [ INFO] [1406340296.340908036]: Searching for device with index = 1
 [ INFO] [1406340296.342048120]: No matching device found.... waiting for devices. Reason: [ERROR] Unable to open specified kinect
 [ INFO] [1406340299.343443561]: Number devices connected: 1
 [ INFO] [1406340299.343618105]: 1. device on bus 000:00 is a Xbox NUI Camera (2ae) from Microsoft (45e) with serial id '0000000000000000'
 [ INFO] [1406340299.346420492]: Searching for device with index = 1
 [ INFO] [1406340299.347807542]: No matching device found.... waiting for devices. Reason: [ERROR] Unable to open specified kinect
 [ INFO] [1406340302.349236789]: Number devices connected: 1
 [ INFO] [1406340302.349391321]: 1. device on bus 000:00 is a Xbox NUI Camera (2ae) from Microsoft (45e) with serial id '0000000000000000'

**Comment by salsaman** [comment]
Hello, trying to test this now. What are the current instructions to test ? I tried following piyushk steps above, but I got an error:

sudo apt-get purge ros-indigo-libfreenect ros-indig-freenect-stack
mkdir -p ~/freenect_ws/src
cd ~/freenect_ws/src
wstool set freenect_stack --git https://github.com/ros-drivers/freenect_stack.git --version-new indigo-devel

ERROR in config: Command requires a target workspace.

**Comment by salsaman** [comment]
Yes there were some odd things with it not finding headers *, but it is working now !


* compiler was not finding freenect_ws/devel_isolated/libfreenect/include/libfreenect/libfreenect_registration.h or freenect_ws/devel_isolated/libfreenect/include/libfreenect/libfreenect.h. It was looking for libfreenect/libfreenect_registration.h and libfreenect/libfreenect.h

**Comment by jack-oquin** [comment]
What is the advantage of using build_type cmake, instead of catkin? Is that mainly to minimize changes to the CMakeLists.txt?

I recommend moving the README.md to another file, where it can be referenced from a new one that explains why this version is specialized as a ROS package.

**Comment by piyushk** [comment]
@jack-oquin Could you elaborate on your comment a bit. I'm not sure I quite follow what you meant here.

**Comment by jack-oquin** [comment]
The existing README.md is for the original OpenKinect/libfreenect repository. Leaving it here will confuse people. Their original README should be retained under some other name, like README_OpenKinect.

We should add our own README, explaining what we have done and why.

**Comment by piyushk** [comment]
@jack-oquin: Using build type cmake does minimize changes to CMakeLists.txt, but also allows for building packages outside the ROS ecosystem. I would recommend doing so for any code that does not have a true ROS dependency.

That's a good point about the README. I will update it once I've got a working release (and before I close this issue).

**Comment by piyushk** [comment]
@salsaman Thanks for testing! It should have resolved those headers automatically. I'm assuming there was a temporary snafu with workspace sourcing. I'll try to get the release out ASAP.

**Comment by salsaman** [comment]
Great ! Any chance of fixing openni now, so we can start doing object detection :-D ?

**Comment by jack-oquin** [comment]
Piyush: I agree about making minimal changes, and that no unnecessary ROS dependencies should be introduced. 

Adding package.xml does no harm. 

Don't forget that we had to [patch many header references](https://github.com/ros-drivers-gbp/libfreenect-release/issues/3) to make the header installation ROS-compliant.

**Comment by piyushk** [comment]
PR for new indigo debs: 
https://github.com/ros/rosdistro/pull/7036
https://github.com/ros/rosdistro/pull/7037

**Comment by ccsmart** [comment]
Greetings and thanks for your time.
Was this implemented ?
Currently trying on armhf Trusty / Indigo but appears to not be.
Is there a test version maybe ?
Thanks

**Comment by piyushk** [comment]
@ccsmart It's been implemented, but the Indigo sync hasn't happened yet, and you're probably still using the old debs. Tully said it would be on Monday. In the meantime, you can try the shadow-fixed ROS repository.
