### ISSUE TITLE
waiting for devices to be connected

### ISSUE THREAD

**Issue by itamab** [ros-drivers/freenect_stack#13]
Hi, I am trying to run "roslaunch freenect_launch freenect.launch" and get a recurrent message:
 No devices connected.... waiting for devices to be connected
The kinect camera is connected and works when running "sudo freenect-glpclview"
I am running indigo with ubunto 14.04
Any ideas?
Thanks

**Comment by jihoonl** [comment]
@piyushk I couldn't get freenect working without tweak while testing freenect in Ubuntu 14.04 to chase https://github.com/turtlebot/turtlebot/issues/171. 

Can you confirm that `ros-indigo-libfreenect` sets up udev rule with fresh installation?

**Comment by piyushk** [comment]
@jihoonl I'm pretty sure that `ros-indigo-libfreenect` ***does not*** set up udev rules on a fresh installation. I don't believe I ever setup the post-install hooks to do so, and I'll have to look into how that can be achieved using bloom.

**Comment by jihoonl** [comment]
I have tested the the instruction in  https://github.com/ros-drivers/freenect_stack/issues/12#issuecomment-63847980 to verify whether Xbox 360 kinect works with new version of `libfreenect`.

I have found that it works fine when `libopenni2-0` or `libfreenect0.2` is installed in the system. It sets up udev rule(40-libopenni2-0.rules) which is required for libfreenect.

**Comment by jihoonl** [comment]
@piyushk do you plan to release `libfreenect` soon?

**Comment by piyushk** [comment]
@jihoonl I'll try my best to get to it, but I'm a bit backlogged with work right now. How soon do you need the new version of libfreenect out?

**Comment by jihoonl** [comment]
I am following up https://github.com/turtlebot/turtlebot/issues/171#issuecomment-68834263 to support both kinect and asus in turtlebot.  Is it possible to get them by next week?

**Comment by jihoonl** [comment]
@piyushk. I would really like to get new deb soon. Is there anything I can help you to speed it up?

**Comment by piyushk** [comment]
I will try and release a new deb today or tomorrow.

**Comment by piyushk** [comment]
https://github.com/ros/rosdistro/pull/7036
https://github.com/ros/rosdistro/pull/7037

**Comment by piyushk** [comment]
@jihoonl: I've verified that ros-indigo-libfreenect v0.5.1 installs the necessary udev rules. I don't have a sensor on hand to test the debs on my indigo machine, but I will do so soon and get back to you.

**Comment by jihoonl** [comment]
```
Invalid argument "/camera_rgb_optical_frame" passed to lookupTransform argument target_frame in tf2 frame_ids cannot start with a '/' like: 
```
I am getting this error when I tried to subscribe `/camera/depth_registered/points` topic.
![screenshot from 2015-02-04 14 39 47](https://cloud.githubusercontent.com/assets/1556736/6035735/c8121dfe-ac7b-11e4-98d7-cbefe7c5aa79.png)
![screenshot from 2015-02-04 14 39 22](https://cloud.githubusercontent.com/assets/1556736/6035736/c8e65b28-ac7b-11e4-93e1-b53505bd47da.png)

**Comment by piyushk** [comment]
This is an issue with tf_prefix in rgbd_launch. See https://github.com/ros-drivers/rgbd_launch/blob/indigo-devel/launch/kinect_frames.launch

However, I didn't think this problem would interrupt normal operation. Are you just getting a warning, or are you getting an error because of this issue?

**Comment by jihoonl** [comment]
Yeah I am in trouble. Rviz does not visualise any point cloud data with this warning.

**Comment by piyushk** [comment]
I will try and reproduce this error today and get back to you.

**Comment by mikeferguson** [comment]
I have run into this in openni2_launch -- we ended up creating a separate launch file for people wanting to use tf_prefix, because tf2 will simply not allow a leading slash:

 * https://github.com/ros-drivers/openni2_launch/commit/3d7d11ef8042e3c48a76b94ad5bd04494cd13ed9
 * https://github.com/ros-drivers/openni2_launch/commit/36982b4838da235d667f826a44cb39797b1a20d6

**Comment by piyushk** [comment]
Thanks @mikeferguson!

While I'm aware of the problem, I was under the impression that it wouldn't affect regular operation. I'm a bit confused as to how I've not seen this error before when testing freenect_launch. Does the problem only exist in indigo and not hydro?

I'll test later tonight and apply the same change to freenect_launch.

**Comment by piyushk** [comment]
Actually, I'm having trouble seeing how your commits solve this problem. 

https://github.com/ros-drivers/rgbd_launch/blob/indigo-devel/launch/kinect_frames.launch still has a default parameter for tf_prefix set to "". Not supplying the parameter or supplying "" should make no difference.

**Comment by piyushk** [comment]
@jihoonl I'm having trouble reproducing the error right, and will be flying to India tomorrow (I only have 1 indigo machine, and as far as I can tell everything seems to be working). I won't be able to work on this issue for 2 weeks. If @mikeferguson's solution works for you, please submit a PR and I'll update this package.

**Comment by jihoonl** [comment]
@mikeferguson solution works for me. @piyushk I have created PR. Could you review it?
