### ISSUE TITLE
freenect_launch: tf_prefix arg missing from Indigo version 

### ISSUE THREAD

**Issue by jack-oquin** [ros-drivers/freenect_stack#18]
The Hydro branch has this argument, but it is missing in Indigo.

**Comment by piyushk** [comment]
@jack-oquin This is on purpose. See #16, #13 for the discussion. You've got to use freenect_tf_prefix.launch in Indigo due to tf2 changes.

I'm now tracking a downstream issue https://github.com/ros/ros_comm/pull/540 to see if we can get back to merging these files in Jade.

**Comment by jack-oquin** [comment]
If that's the case, we need to introduce a ``freenect_tf_prefix.launch`` in the Hydro version. so dependent packages can work with both releases.

**Comment by piyushk** [comment]
@jack-oquin That's a great idea. I'll try and test it out soon.
