### ISSUE TITLE
Create a hydro-devel branch, use master in place of indigo-devel and make that the default branch.

### ISSUE THREAD

**Issue by piyushk** [ros-drivers/freenect_stack#19]

**Comment by piyushk** [comment]
Closed via https://github.com/ros/rosdistro/pull/7889

**Comment by jack-oquin** [comment]
Do you want to update the indigo distribution.yaml to use master, instead of indigo-devel?

I can see doing it either way.

**Comment by piyushk** [comment]
Due to a mistake I made earlier,  it's already set to master. The indigo-devel branch no longer exists.

**Comment by jack-oquin** [comment]
Sounds good. 

I usually postpone creating devel branches until I have to make a change that does not also apply to later releases.
