### ISSUE TITLE
tf publishing rates for camera_rgb_optical_frame and camera_depth_optical_frame are very slow

### ISSUE THREAD

**Issue by JoeMWatson** [ros-drivers/freenect_stack#24]
hello, 

I'm having some trouble with using the kinect with other software because the above transforms are published at 10.175Hz on average, whereas tfs are typically published at around 50Hz. This is causing a lot of synchronization issues e.g. 'Lookup would require extrapolation into the past'. Do you have any idea what is causing the lag and how I could speed it up?

**Comment by piyushk** [comment]
@JoeMWatson Apologies for the delayed response. I don't know. tf frames are published at 100Hz: https://github.com/ros-drivers/rgbd_launch/blob/indigo-devel/launch/kinect_frames.launch

I suspect this problem is probably specific to your system. Please reopen if otherwise.
